config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  resources :lounges do
    resources :display_images, only: [:destroy]
    resources :logos, only: [:destroy]
    resources :events, shallow: true
    resources :memberships, shallow: true
    resources :special_offers, shallow: true
  end

  resources :events do
    resources :event_flyers, only: [:destroy]
    resources :rsvps, shallow: true
  end

  resources :lounges, only: :index do
    member do
      post 'toggle_favorite', to: 'lounges#toggle_favorite'
    end
  end

  resources :memberships do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :notifications do
    member do
      post :read
      post :unread
    end
  end

  resources :rsvps do
    member do
      patch :mark_attended
      patch :mark_unattended
    end
  end

  resources :special_offers do
    resources :special_offer_flyers, only: [:destroy]
  end

  resources :subscriptions

  namespace :purchase do
    post 'create-monthly-email-checkout-session', to: 'checkouts#create_monthly_email_checkout_session'
    post 'create-monthly-email-and-text-checkout-session', to: 'checkouts#create_monthly_email_and_text_checkout_session'
    post 'create-yearly-email-checkout-session', to: 'checkouts#create_yearly_email_checkout_session'
    post 'create-yearly-email-and-text-checkout-session', to: 'checkouts#create_yearly_email_and_text_checkout_session'
  end

  get 'my_lounges', to: 'lounges#my_lounges'
  get 'pricing', to: 'price_listings#pricing'
  get 'success', to: 'purchase/checkouts#success'
  get 'billing', to: 'billing#show'

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server.new, at: '/jobs'
  end
end

app/models/special_offer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: special_offers
#
#  id                 :bigint           not null, primary key
#  description        :text
#  end_date           :date
#  members_only       :boolean          default(FALSE)
#  special_offer_type :string
#  start_date         :date
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  lounge_id          :bigint           not null
#
# Indexes
#
#  index_special_offers_on_lounge_id  (lounge_id)
#
# Foreign Keys
#
#  fk_rails_...  (lounge_id => lounges.id)
#
class SpecialOffer < ApplicationRecord
  SPECIAL_OFFER_TYPES = ['Buy One, Get One (BOGO)', 'Discount', 'Brand', 'Members Only', 'Holiday'].freeze

  belongs_to :lounge

  has_one_attached :flyer

  validates_presence_of :description, :special_offer_type, :start_date, :end_date
  validates :description, length: { maximum: 500 }

  after_commit :notify_followers_and_or_members, on: :create
  after_commit :update_followers_and_or_members, on: :update
  after_commit :cancel_follower_and_or_members, on: :destroy

  paginates_per 10

  def self.search(search)
    where('special_offer_type = ?', search.titleize) if search
  end

  private

  def notify_followers_and_or_members
    if members_only?
      notify_members
      new_special_offer_text_for_members
    else
      notify_followers
      new_special_offer_text_for_followers
    end
  end

  def update_followers_and_or_members
    if members_only?
      update_members
      updated_special_offer_text_for_members
    else
      update_followers
      update_special_offer_text_for_followers
    end
  end

  def cancel_follower_and_or_members
    if members_only?
      cancellation_special_offer_members
      cancelled_special_offer_text_for_members
    else
      cancellation_special_offer_followers
      cancelled_special_offer_text_for_followers
    end
  end

  def new_special_offer_text_for_members
    return if lounge.memberships.empty?

    text_all_members(lounge.memberships, new_special_offer_message_for_members)
  end

  def text_all_members(memberships, message)
    members_phone_numbers = memberships.where(active: true).pluck(:phone_number).compact

    members_phone_numbers.each do |phone_number|
      TwilioClient.new.send_text(phone_number, message)
    end
  end

  def new_special_offer_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, new_special_offer_message_for_followers)
  end

  def text_all_favoritors(favoritors, message)
    favoritors_phone_numbers = favoritors.pluck(:phone_number).compact

    favoritors_phone_numbers.each do |phone_number|
      TwilioClient.new.send_text(phone_number, message)
    end
  end

  def updated_special_offer_text_for_members
    return if lounge.memberships.empty?

    text_all_members(lounge.memberships, updated_special_offer_message)
  end

  def update_special_offer_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, updated_special_offer_message)
  end

  def cancelled_special_offer_text_for_members
    return if lounge.memberships.empty?

    text_all_members(lounge.memberships, cancelled_special_offer_message)
  end

  def cancelled_special_offer_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, cancelled_special_offer_message)
  end

  def new_special_offer_message_for_members
    %(New Members Only #{special_offer_type} special offer from #{lounge.name}!
      Here are the details: #{description}
      Begins: #{start_date.strftime('%b %e, %Y')}
      Ends: #{end_date.strftime('%b %e, %Y')})
  end

  def new_special_offer_message_for_followers
    %(New #{special_offer_type} special offer from #{lounge.name}!
      Here are the details: #{description}
      Begins: #{start_date.strftime('%b %e, %Y')}
      Ends: #{end_date.strftime('%b %e, %Y')})
  end

  def updated_special_offer_message
    %(The #{special_offer_type} special offer from #{lounge.name} has been updated.
      Here are the latest details: #{description}
      Begins: #{start_date.strftime('%b %e, %Y')}
      Ends: #{end_date.strftime('%b %e, %Y')})
  end

  def cancelled_special_offer_message
    %(The #{special_offer_type} special offer, has been cancelled.
      Please contact #{lounge.name} at: #{lounge.phone} for additional information.
      Thank you.)
  end

  def notify_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      NewSpecialOfferMailer.with(favoritor: favoritor, special_offer: self).notify_followers.deliver_later
    end
  end

  def notify_members
    lounge.memberships.where(active: true).each do |membership|
      NewSpecialOfferMailer.with(membership: membership, special_offer: self).notify_members.deliver_later
    end
  end

  def update_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      UpdateSpecialOfferMailer.with(favoritor: favoritor, special_offer: self).notify_followers.deliver_later
    end
  end

  def update_members
    lounge.memberships.where(active: true).each do |membership|
      UpdateSpecialOfferMailer.with(membership: membership, special_offer: self).notify_members.deliver_later
    end
  end

  def cancellation_special_offer_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      CancelledSpecialOfferMailer.with(favoritor: favoritor, special_offer: self).notify_followers.deliver_later
    end
  end

  def cancellation_special_offer_members
    lounge.memberships.where(active: true).each do |membership|
      CancelledSpecialOfferMailer.with(membership: membership, special_offer: self).notify_members.deliver_later
    end
  end
end

app/controllers/special_offers_controller.rb
# frozen_string_literal: true

class SpecialOffersController < ApplicationController
  before_action :set_special_offer, only: %i[show edit update destroy]
  before_action :set_lounge, only: %i[index new create]

  def index
    @special_offers = if params[:search].present?
                        SpecialOffer.search(params[:search]).order(created_at: :desc).page(params[:page])
                      else
                        @lounge.special_offers.order(created_at: :desc).page(params[:page])
                      end
  end

  def show; end

  def new
    @special_offer = @lounge.special_offers.build
    authorize @special_offer
  end

  def edit; end

  def create
    @special_offer = @lounge.special_offers.build(special_offer_params)

    # Pundit check
    authorize @special_offer

    respond_to do |format|
      if @special_offer.save
        format.turbo_stream { redirect_to special_offer_path(@special_offer) }
        format.html { redirect_to special_offer_url(@special_offer), notice: 'Special offer was successfully created.' }
        format.json { render :show, status: :created, location: @special_offer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      # Pundit check
      authorize @special_offer

      if @special_offer.update(special_offer_params)
        format.turbo_stream { redirect_to [@lounge, @special_offer] }
        format.html do
          redirect_to special_offer_url(@special_offer), notice: 'Special offer was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @special_offer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @special_offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # Pundit check
    authorize @special_offer

    @special_offer.destroy

    redirect_to root_path, status: :see_other
    flash[:notice] = 'Special offer successfully deleted.'
  end

  private

  def set_special_offer
    @special_offer = SpecialOffer.find(params[:id])
  end

  def set_lounge
    @lounge = Lounge.friendly.find(params[:lounge_id])
  end

  def special_offer_params
    params.require(:special_offer).permit(:special_offer_type, :description, :flyer, :members_only, :start_date,
                                          :end_date, :lounge_id, :search)
  end
end

app/helpers/special_offers_helper.rb
module SpecialOffersHelper
end

app/views/special_offers/_form.html.erb
<%= bootstrap_form_with(model: [@lounge, special_offer]) do |form| %>
  <% if special_offer.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(special_offer.errors.count, "error") %> prohibited this special offer from being saved:</h2>

    <ul>
      <% special_offer.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <div class="control">
    <%= form.select :special_offer_type, SpecialOffer::SPECIAL_OFFER_TYPES %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= form.text_area :description %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= form.date_field :start_date, min: Date.today %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= form.date_field :end_date, min: Date.today %>
  </div>
</div>

<div class="field">
  <div class="control">
    <% if special_offer.flyer.present? %>
      <div id="<%= dom_id(special_offer, :flyer) %>">
        <%= image_tag special_offer.flyer, size: "300x300" %>
          <%= link_to "Remove flyer", special_offer_special_offer_flyer_path(@special_offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      <% end %>
    <%= form.file_field :flyer %>
  </div>
</div>

<div class="field">
  <div class="control">
    <%= form.check_box :members_only %>
  </div>
</div>

<div class="control">
  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/special_offers/_special_offer.html.erb
<div id="<%= dom_id special_offer %>">
  <p>
    <strong>Description:</strong>
    <%= special_offer.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= special_offer.start_date.strftime('%b %e, %Y')%>
  </p>

  <p>
    <strong>End date:</strong>
    <%= special_offer.end_date.strftime('%b %e, %Y') %>
  </p>
</div>

app/views/special_offers/edit.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class='mb-3'>Editing special offer</h1>

      <%= render "form", special_offer: @special_offer %>
      <%= link_to "Back to special offers", lounge_special_offers_path(@special_offer.lounge) %>
    </div>
  </div>
</div>

app/views/special_offers/index.html.erb
<p style="color: green"><%= notice %></p>
<!-- ======= Special Offers Index Section ======= -->
<section id="portfolio-details" class="portfolio-details" style="padding-top: 150px">
  <div class="container">
    <div class="row gy-4">

    <h1>Total Special offers: <%= @special_offers.page(1).per(10).total_count %></h1>

    <div class="d-flex bd-highlight mb-3">
      <div class="p-2 bd-highlight">
        <%= form_tag(lounge_special_offers_path(@lounge), method: :get) do %>
          <%= text_field_tag(:search, params[:search], placeholder: 'Type') %>
          <%= submit_tag("Search" , class: "btn btn-warning") %>
        <% end %>
      </div>

      <div class="ms-auto p-2 bd-highlight">
        <%= link_to "New special offer", new_lounge_special_offer_path(@lounge), class: 'btn btn-warning' %>
      </div>
    </div>

    <table class="table">
      <thead>
        <tr>
          <th scope="col">Flyer</th>
          <th scope="col">Type</th>
          <th scope="col">Description</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col">Members Only?</th>
          <th scope="col">Edit</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @special_offers.each do |special_offer| %>
          <tr>
            <td><%= special_offer.flyer.present? ? image_tag(special_offer.flyer, size: '30x30') : 'No Flyer' %></td>
            <td><%= special_offer.special_offer_type %></td>
            <td><%= special_offer.description %></td>
            <td><%= special_offer.start_date.strftime('%b %e, %Y') %></td>
            <td><%= special_offer.end_date.strftime('%b %e, %Y') %></td>
            <td><%= special_offer.members_only ? 'Yes' : 'No' %></td>
            <td><%= button_to "Edit", "/special_offers/#{special_offer.id}/edit", method: :get, class: "btn btn-secondary" %></td>
            <td><%= link_to "Delete", special_offer_path(special_offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <% if @special_offers.count > 1 %>
      <%= paginate @special_offers %>
    <% end %>
  </div>
</section>

app/views/special_offers/new.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class='mb-3'>New Special Offer</h2>
      
      <%= render "form", special_offer: @special_offer %>
      <%= link_to "Back to special offers", lounge_special_offers_path(@lounge) %>
    </div>
  </div>
</div>

app/views/special_offers/show.html.erb
<section id="portfolio-details" class="portfolio-details" style="padding-top: 150px">
  <div class="pt-5 mt-5">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class='mb-3'><%= "#{@special_offer.special_offer_type} special offer from #{@special_offer.lounge.name}" %></h2>
        <div class="pic"><%= image_tag @special_offer.flyer, size: "100x100" if @special_offer.flyer.present? %></div>
        <p style="color: green"><%= notice %></p>

        <%= render @special_offer %>

        <div>
          <% if user_signed_in? && current_user.id == @special_offer.lounge.user_id %>
            <%= link_to "Edit this special offer", edit_special_offer_path(@special_offer) %> |
            <%= link_to "Back to special offers", lounge_special_offers_path(@special_offer.lounge) %> |
            <%= link_to "Delete", special_offer_path(@special_offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button is-primary is-light card-footer-item" %>
          <% else %>
            <%= link_to "Back to special offers", lounge_special_offers_path(@special_offer.lounge) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>