config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  resources :lounges do
    resources :display_images, only: [:destroy]
    resources :logos, only: [:destroy]
    resources :events, shallow: true
    resources :memberships, shallow: true
    resources :special_offers, shallow: true
  end

  resources :events do
    resources :event_flyers, only: [:destroy]
    resources :rsvps, shallow: true
  end

  resources :lounges, only: :index do
    member do
      post 'toggle_favorite', to: 'lounges#toggle_favorite'
    end
  end

  resources :memberships do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :notifications do
    member do
      post :read
      post :unread
    end
  end

  resources :rsvps do
    member do
      patch :mark_attended
      patch :mark_unattended
    end
  end

  resources :special_offers do
    resources :special_offer_flyers, only: [:destroy]
  end

  resources :subscriptions

  namespace :purchase do
    post 'create-monthly-email-checkout-session', to: 'checkouts#create_monthly_email_checkout_session'
    post 'create-monthly-email-and-text-checkout-session', to: 'checkouts#create_monthly_email_and_text_checkout_session'
    post 'create-yearly-email-checkout-session', to: 'checkouts#create_yearly_email_checkout_session'
    post 'create-yearly-email-and-text-checkout-session', to: 'checkouts#create_yearly_email_and_text_checkout_session'
  end

  get 'my_lounges', to: 'lounges#my_lounges'
  get 'pricing', to: 'price_listings#pricing'
  get 'success', to: 'purchase/checkouts#success'
  get 'billing', to: 'billing#show'

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server.new, at: '/jobs'
  end
end

app/models/lounge.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: lounges
#
#  id                     :bigint           not null, primary key
#  address_street_1       :string
#  address_street_2       :string
#  city                   :string
#  details                :text
#  email                  :string
#  featured               :boolean          default(FALSE)
#  name                   :string
#  outside_cigars_allowed :boolean          default(FALSE)
#  outside_drinks_allowed :boolean          default(FALSE)
#  phone                  :string
#  slug                   :string
#  state                  :string
#  time_zone              :string
#  weekday_closing_hour   :string
#  weekday_opening_hour   :string
#  weekend_closing_hour   :string
#  weekend_opening_hour   :string
#  zip_code               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_id                :bigint           not null
#
# Indexes
#
#  index_lounges_on_slug     (slug) UNIQUE
#  index_lounges_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Lounge < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  HOURS_DISPLAY = ['Closed', '12:00 AM', '1:00 AM', '2:00 AM', '3:00 AM', '4:00 AM', '5:00 AM', '6:00 AM', '7:00 AM',
                   '8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM', '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM', '5:00 PM', '6:00 PM', '7:00 PM',
                   '8:00 PM', '9:00 PM', '10:00 PM', '11:00 PM', '12:00 PM'].freeze

  TIME_ZONES = ['Eastern Time', 'Central Time', 'Mountain Time', 'Pacific Time', 'Alaska Time',
                'Hawaii-Aleutian Time'].freeze

  belongs_to :user

  has_many :events, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :special_offers, dependent: :destroy

  has_one_attached :logo
  has_one_attached :display_image

  validates_presence_of :name, :address_street_1, :city, :state, :zip_code, :phone, :email
  validates :email, uniqueness: true
  validates :email,
            format: { with: /\A^(.+)@(.+)$\z/, message: 'Email invalid' },
            uniqueness: { case_sensitive: false },
            length: { minimum: 4, maximum: 255 }

  validates :name, uniqueness: {
    scope: %i[address_street_1 city state zip_code],
    message: 'A lounge already exists at this location.'
  }
  validates :details, length: { maximum: 1000, too_long: '%<count>s characters is the maximum allowed.' }

  validates_format_of :zip_code,
                      with: /\A\d{5}-\d{4}|\A\d{5}\z/,
                      message: 'should be 12345 or 12345-1234'

  validates :logo, file_size: { less_than_or_equal_to: 5.megabytes },
                   file_content_type: { allow: ['image/jpeg', 'image/png'] }

  validates :display_image, file_size: { less_than_or_equal_to: 5.megabytes },
                            file_content_type: { allow: ['image/jpeg', 'image/png', 'image/jpg'] }

  scope :featured, -> { where(featured: true) }

  acts_as_favoritable

  paginates_per 10
end

app/controllers/lounges_controller.rb
# frozen_string_literal: true

class LoungesController < ApplicationController
  before_action :set_lounge, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  def index
    @lounges = Lounge.all.order(:created_at).page(params[:page])
  end

  def show; end

  def new
    @lounge = current_user.lounges.build
    authorize @lounge
  end
  
  def edit; end
  
  def create
    @lounge = current_user.lounges.build(lounge_params)

    # Pundit check 
    authorize @lounge

    respond_to do |format|
      if @lounge.save
        format.turbo_stream { redirect_to lounge_url(@lounge) }
        flash[:notice] = 'Lounge successfully created.'
        format.html { redirect_to lounge_url(@lounge) }
        format.json { render :show, status: :created, location: @lounge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lounge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      # Pundit check
      authorize @lounge

      if @lounge.update(lounge_params)
        format.turbo_stream { redirect_to lounge_url(@lounge) }
        flash[:notice] = 'Lounge successfully updated.'
        format.html { redirect_to lounge_url(@lounge), notice: 'Lounge was successfully updated.' }
        format.json { render :show, status: :ok, location: @lounge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lounge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # Pundit check
    authorize @lounge
    @lounge.destroy

    redirect_to root_path, status: :see_other
    flash[:notice] = 'Lounge successfully deleted.'
  end

  def toggle_favorite
    @lounge = Lounge.friendly.find(params[:id])
    current_user.favorited?(@lounge) ? current_user.unfavorite(@lounge) : current_user.favorite(@lounge)
  end

  def my_lounges
    @current_user_lounges = current_user.lounges
  end

  private

  def set_lounge
    @lounge = Lounge.friendly.find(params[:id])
  end

  def lounge_params
    params.require(:lounge).permit(:name, :email, :phone, :address_street_1, :address_street_2, :city, :state, :zip_code, :details,
                                   :hours, :logo, :outside_cigars_allowed, :outside_drinks_allowed, :weekday_opening_hour, :weekday_closing_hour,
                                   :weekend_opening_hour, :weekend_closing_hour, :display_image)
  end
end

app/helpers/lounges_helper.rb
module LoungesHelper
end

app/views/lounges/_form.html.erb
<%= bootstrap_form_for(@lounge) do |form| %>
  <% if lounge.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(lounge.errors.count, "error") %> prohibited this lounge from being saved:</h2>

        <ul>
          <% lounge.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <div class="control">
        <%= form.text_field :name %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.text_field :address_street_1 %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.text_field :address_street_2 %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :state, CS.states(:us).invert, { prompt: "Select a state" } %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.text_field :city %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.text_field :zip_code %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.email_field :email %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.telephone_field :phone %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :weekday_opening_hour, Lounge::HOURS_DISPLAY %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :weekday_closing_hour, Lounge::HOURS_DISPLAY %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :weekend_opening_hour, Lounge::HOURS_DISPLAY %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :weekend_closing_hour, Lounge::HOURS_DISPLAY %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.select :time_zone, Lounge::TIME_ZONES %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.text_area :details, placeholder: "Tell us about your lounge." %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.check_box :outside_drinks_allowed  %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= form.check_box :outside_cigars_allowed %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <% if lounge.logo.present? %>
          <div id="<%= dom_id(lounge, :logo) %>">
            <%= image_tag lounge.logo, size: "300x300"%>
            <%= link_to "Remove logo", lounge_logo_path(@lounge), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
        <% end %>
        <%= form.file_field :logo %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <% if lounge.display_image.present? %>
         <div id="<%= dom_id(lounge, :display_image) %>">
            <%= image_tag lounge.display_image, size: "300x300"  %>
            <%= link_to "Remove display image", lounge_display_image_path(@lounge), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
        <% end %>
        <%= form.file_field :display_image %>
      </div>
    </div>

    <div class="field">
      <%= form.submit "Save" %>
    </div>
  <% end %>

app/views/lounges/_lounge.html.erb
<!-- ======= Lounge Details Section ======= -->
<section id="portfolio-details" class="portfolio-details" style="padding-top: 150px">
  <div class="container">
    <div class="row gy-4">

      <div class="col-lg-8">
        <div class="portfolio-details-slider swiper">
          <div class="swiper-wrapper align-items-center">
          <% if lounge.display_image.present? %>
            <div class="swiper-slide mb-2">
              <%= image_tag(lounge.display_image) %>
            </div>
          <% else %>
            <h3><i class="bi bi-camera">No images available</i></h3>
          <% end %>
          </div>
          <div class="swiper-pagination"></div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="portfolio-info">
          <div class="d-flex justify-content-start">
            <%= image_tag(lounge.logo) if lounge.logo.present? %>
          </div>
          <div class="d-flex justify-content-start pt-3">
            <h3><%= lounge.name %></h3>
          </div>
          <ul>
            <li><strong>Address</strong>:  <%= lounge.address_street_1 %>, <%= lounge.address_street_2 %></li>
            <li><strong>City</strong>: <%= lounge.city %></li>
            <li><strong>State</strong>: <%= lounge.state %></li>
            <li><strong>Phone</strong>: (917) 223-3344</li>
            <li><strong>Email</strong>: <%= lounge.email %></li>
          </ul>
          <% if user_signed_in? && current_user.id == lounge.user_id %>
            <div class="d-flex justify-content-around">
              <%= link_to "Edit Lounge", edit_lounge_path(lounge), class: "btn btn-warning" %>
              <%= link_to "New Event", new_lounge_event_path(lounge), class: "btn btn-warning" %>
              <%= link_to "View Events", lounge_events_path(lounge), class: "btn btn-warning" %>
            </div>
            <div class="d-flex justify-content-around pt-3">
              <%= link_to "Memberships", lounge_memberships_path(lounge), class: "btn btn-warning" %>
              <%= link_to "Special Offers", lounge_special_offers_path(lounge), class: "btn btn-warning"%>
              <%= link_to "Delete", lounge_path(lounge), class: "btn btn-warning", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </div>
          <% else %>
            <div class="d-flex justify-content-between">
              <%= link_to "View Events", lounge_events_path(lounge) %>
              <%= link_to "Special Offers", lounge_special_offers_path(lounge)%>
            </div>
          <% end %>
        </div>
        <div class="portfolio-description">
          <h4>About <%= lounge.name %></h4>
          <p><%= lounge.details %></p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/lounges/edit.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1 class="has-text-weight-bold pb-3 is-size-3">Editing lounge</h1>
      <%= render "form", lounge: @lounge %>
    </div>
  </div>
</div>

app/views/lounges/index.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p style="color: green"><%= notice %></p>

      <h1>Lounges</h1>

      <div id="lounges">
        <% @lounges.each do |lounge| %>
          <%= render lounge %>
          <p>
            <%= link_to "Show this lounge", lounge %>
          </p>
        <% end %>
      </div>
        <%= paginate @lounges %>
    </div>
  </div>
</div>

app/views/lounges/my_lounges.html.erb
<div id="lounges">
  <% @current_user_lounges.each do |lounge| %>
    <%= render lounge %>
  <% end %>
</div>

app/views/lounges/new.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="mb-3">Lounge Details</h2>

      <%= render "form", lounge: @lounge %>
    </div>
  </div>
</div>

app/views/lounges/show.html.erb
<%= render @lounge %>