config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  resources :lounges do
    resources :display_images, only: [:destroy]
    resources :logos, only: [:destroy]
    resources :events, shallow: true
    resources :memberships, shallow: true
    resources :special_offers, shallow: true
  end

  resources :events do
    resources :event_flyers, only: [:destroy]
    resources :rsvps, shallow: true
  end

  resources :lounges, only: :index do
    member do
      post 'toggle_favorite', to: 'lounges#toggle_favorite'
    end
  end

  resources :memberships do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :notifications do
    member do
      post :read
      post :unread
    end
  end

  resources :rsvps do
    member do
      patch :mark_attended
      patch :mark_unattended
    end
  end

  resources :special_offers do
    resources :special_offer_flyers, only: [:destroy]
  end

  resources :subscriptions

  namespace :purchase do
    post 'create-monthly-email-checkout-session', to: 'checkouts#create_monthly_email_checkout_session'
    post 'create-monthly-email-and-text-checkout-session', to: 'checkouts#create_monthly_email_and_text_checkout_session'
    post 'create-yearly-email-checkout-session', to: 'checkouts#create_yearly_email_checkout_session'
    post 'create-yearly-email-and-text-checkout-session', to: 'checkouts#create_yearly_email_and_text_checkout_session'
  end

  get 'my_lounges', to: 'lounges#my_lounges'
  get 'pricing', to: 'price_listings#pricing'
  get 'success', to: 'purchase/checkouts#success'
  get 'billing', to: 'billing#show'

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server.new, at: '/jobs'
  end
end

app/models/event.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: events
#
#  id                :bigint           not null, primary key
#  end_time          :time
#  event_date        :date
#  event_description :text
#  event_type        :string           not null
#  event_url         :string
#  maximum_capacity  :integer
#  members_only      :boolean          default(FALSE)
#  name              :string           not null
#  rsvp_needed       :boolean          default(FALSE)
#  slug              :string
#  start_time        :time
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  lounge_id         :bigint           not null
#
# Indexes
#
#  index_events_on_lounge_id  (lounge_id)
#  index_events_on_slug       (slug) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (lounge_id => lounges.id)
#
class Event < ApplicationRecord
  TYPES = ['Live Music', 'Whiskey Tasting', 'Cigar Brand Event', 'Holiday', 'Sports', 'Virtual'].freeze

  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :lounge
  has_many :rsvps, dependent: :destroy

  has_one_attached :flyer

  validates_presence_of :end_time, :event_date, :event_type, :name, :start_time
  validates :event_description, length: { maximum: 1000, too_long: '%<count>s characters is the maximum allowed.' }
  validates :event_url, url: true, if: proc { |event| event.event_type == 'Virtual' }
  validate :end_date_not_after_start_date, :end_time_not_earlier_than_start_time

  paginates_per 10

  def self.send_reminder_text
    events_within_24_hours = where(event_date: Date.today + 1.day)
    return if events_within_24_hours.empty?

    events_within_24_hours.each do |event|
      reminder_message = %(
        Reminder, the #{event.name} event hosted by #{event.lounge.name} is tomorrow.
        Here are the details:
        Event: #{event.name}
        Date: #{event.event_date.strftime('%b %e, %Y')}
        Start Time: #{event.start_time.strftime('%l:%M %P')}
        End Time: #{event.end_time.strftime('%l:%M %P')}
        Location: #{event.lounge.address_street_1}, #{event.lounge.city}, #{event.lounge.state}, #{event.lounge.zip_code}
        Phone: #{event.lounge.phone}
      )
      event.lounge.memberships.active.each do |membership|
        TwilioClient.new.send_text(membership&.phone_number, reminder_message, event)
      end
    end
  end

  def self.send_reminder_email
    events_within_24_hours = where(event_date: Date.today + 1.day)
    return if events_within_24_hours.empty?

    events_within_24_hours.each do |event|
      event.lounge.memberships.active.each do |membership|
        OneDayReminderMailer.with(membership: membership, event: event).remind_members
        puts 'Email sent'
      end
    end
  end

  private

  def notify_followers_and_or_members
    if members_only?
      notify_members
      new_event_text_for_members
    else
      notify_members
      new_event_text_for_members
      notify_followers
      new_event_text_for_followers
    end
  end

  def update_followers_and_or_members
    if members_only?
      update_members
      updated_event_text_for_members
    else
      update_members
      updated_event_text_for_members
      update_followers
      updated_event_text_for_followers
    end
  end

  def cancel_follower_and_or_members
    if members_only?
      cancellation_event_members
      cancelled_event_text_for_members
    else
      cancellation_event_members
      cancelled_event_text_for_members
      cancellation_event_followers
      cancelled_event_text_for_followers
    end
  end

  def end_date_not_after_start_date
    return if event_date.blank?

    errors.add(:event_date, 'Event date cannot be in the past') if event_date < Date.today
  end

  def end_time_not_earlier_than_start_time
    return if end_time.blank? || start_time.blank?

    errors.add(:end_time, 'End time cannot be earlier than start time.') if end_time.before?(start_time)
  end

  def notify_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      NotifyFollowersMailer.with(favoritor: favoritor, event: self).notify_followers.deliver_later
    end
  end

  def update_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      UpdatedEventNotificationMailer.with(favoritor: favoritor, event: self).update_notify_followers.deliver_later
    end
  end

  def cancellation_event_followers
    return if lounge.favoritors.empty?

    lounge.favoritors.each do |favoritor|
      CancelledEventNotificationMailer.with(favoritor: favoritor, event: self).cancel_notify_followers.deliver_later
    end
  end

  def new_event_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, new_event_message)
  end

  def updated_event_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, updated_event_message)
  end

  def cancelled_event_text_for_followers
    return if lounge.favoritors.empty?

    text_all_favoritors(lounge.favoritors, cancelled_event_message)
  end

  def update_rsvps_text
    return if rsvps.nil?

    rsvps.each do |rsvp|
      next if rsvp.phone_number.blank?

      TwilioClient.new.send_text(rsvp.phone_number, rsvp_update_message)
    end
  end

  def cancel_rsvps_text
    return if rsvps.nil?

    rsvps.each do |rsvp|
      next if rsvp.phone_number.blank?

      TwilioClient.new.send_text(rsvp.phone_number, rsvp_cancellation_message)
    end
  end

  def text_all_favoritors(favoritors, message)
    favoritors_phone_numbers = favoritors.pluck(:phone_number).compact

    favoritors_phone_numbers.each do |phone_number|
      TwilioClient.new.send_text(phone_number, message)
    end
  end

  def rsvp_update_message
    %(#{rsvp.user.first_name}, your RSVP has been updated for the
      #{name} event, hosted by #{lounge.name}!
      Here are the latest details:
      Event: #{name}
      Date: #{event_date.strftime('%b %e, %Y')}
      Start Time: #{start_time.strftime('%l:%M %P')}
      End Time: #{end_time.strftime('%l:%M %P')}
      Location: #{lounge.address_street_1}, #{event.lounge.city}, #{event.lounge.state}, #{event.lounge.zip_code}
      Phone: #{lounge.phone})
  end

  def rsvp_cancellation_message
    %(Hi #{rsvp.user.first_name}, the
      #{name} event, hosted by #{lounge.name} has been cancelled.
      Please contact #{lounge.name} at #{lounge.phone} for more information.)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_lounge, only: %i[index new create]

  def index
    @events = @lounge.events.order(:created_at).page(params[:page])
  end

  def show; end

  def new
    @event = @lounge.events.build
    authorize @event
  end

  def edit; end

  def create
    @event = @lounge.events.build(event_params)

    # Pundit check
    authorize @event

    respond_to do |format|
      if @event.save
        EventNotificationService.new(@event).new_notification
        format.turbo_stream { redirect_to event_path(@event) }
        format.html { redirect_to lounge_event_url(@event), notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      # Pundit check
      authorize @event

      if @event.update(event_params)
        EventNotificationService.new(@event).update_notification
        format.turbo_stream { redirect_to [@lounge, @event] }
        format.html { redirect_to lounge_event_url(@event), notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # Pundit check
    authorize @event
    EventNotificationService.new(@event).cancellation_notification
    @event.destroy

    redirect_to root_path, status: :see_other
    flash[:notice] = 'Event successfully deleted.'
  end

  private

  def set_event
    @event = Event.friendly.find(params[:id])
  end

  def set_lounge
    @lounge = Lounge.friendly.find(params[:lounge_id])
  end

  def event_params
    params.require(:event).permit(:name, :end_time, :event_type, :event_url, :maximum_capacity, :members_only, :rsvp_needed, :start_time, :event_date,
                                  :lounge_id, :flyer, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
  <!-- ======= Event Section ======= -->
<section id="team" class="team ">
  <div id="<%= dom_id event %>", class="pb-3">
    <div class="container">
      <div class="row">
          <div class="col-lg-12">
            <div class="member d-flex align-items-start">
              <div class="pic"><%= image_tag event.flyer, size: "100x100" if event.flyer.present? %></div>
              <div class="member-info">
                <h4><%= event.name %></h4>
                <span><%= event.event_type %> | <%= event.event_date.strftime("%b %e, %Y") %> | <%= event.start_time.strftime('%l:%M %P') %> - <%= event.end_time.strftime('%l:%M %P') %></span>
                <p><%= event.event_description %></p>
                <div class="pt-3">
                  <% if user_signed_in? && current_user.id == event.lounge.user_id %>
                    <%= link_to "Edit this event", "/events/#{event.id}/edit", class: "button is-primary is-light card-footer-item" %>
                    <%= link_to "Delete", event_path(event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button is-primary is-light card-footer-item" %>
                    <%= link_to "Event Details", event_path(event), class: "button is-primary is-light" %>
                  <% elsif user_signed_in? %>
                    <%= link_to "RSVP Here", "#", class: "button is-primary is-light" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</section>

app/views/events/_form.html.erb
<%= bootstrap_form_with(model: [@lounge, event]) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="control">
      <%= form.text_field :name %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.date_field :event_date, min: Date.today %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.select :event_type, Event::TYPES %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.time_field :start_time %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.time_field :end_time %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.number_field :maximum_capacity, in: 1..100, step: 1 %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.text_area :event_description %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <% if event.flyer.present? %>
        <div id="<%= dom_id(event, :flyer) %>">
          <%= image_tag event.flyer, size: "300x300" %>
            <%= link_to "Remove flyer", event_event_flyer_path(@event), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
        <% end %>
      <%= form.file_field :flyer %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.check_box :members_only %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= form.url_field :event_url, placeholder: "https://www.example.com" %>
    </div>
  </div>

  <div class="control">
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h2 class="mb-3">Editing <%= @event.name%></h2>

      <%= render "form", event: @event %>
      <%= link_to "Back to events", lounge_events_path(@event.lounge) %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="is-size-3 pb-3"> Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
  <% end %>

  <div class="d-flex justify-content-center">
    <% if user_signed_in? && current_user.id == @events&.first&.lounge&.user_id %>
      <%= link_to "New Event", new_lounge_event_path(@lounge), class: "button is-primary is-light card-footer-item" %>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @events %>
  </div>
</div>

app/views/events/new.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render "form", event: @event %>

      <%= link_to "Back to Events", lounge_events_path(@lounge) %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="pt-5 mt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <p style="color: green"><%= notice %></p>

      <%= render @event %>
      <%= link_to "Back to Events", lounge_events_path(@event.lounge) %> |
      <%= link_to "RSVP Here", new_event_rsvp_path(@event), class: "button is-primary is-light" %>
    </div>
  </div>
</div>