config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get 'users', to: 'devise/sessions#new'
  end

  resources :lounges do
    resources :display_images, only: [:destroy]
    resources :logos, only: [:destroy]
    resources :events, shallow: true
    resources :memberships, shallow: true
    resources :special_offers, shallow: true
  end

  resources :events do
    resources :event_flyers, only: [:destroy]
    resources :rsvps, shallow: true
  end

  resources :lounges, only: :index do
    member do
      post 'toggle_favorite', to: 'lounges#toggle_favorite'
    end
  end

  resources :memberships do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :notifications do
    member do
      post :read
      post :unread
    end
  end

  resources :rsvps do
    member do
      patch :mark_attended
      patch :mark_unattended
    end
  end

  resources :special_offers do
    resources :special_offer_flyers, only: [:destroy]
  end

  resources :subscriptions

  namespace :purchase do
    post 'create-monthly-email-checkout-session', to: 'checkouts#create_monthly_email_checkout_session'
    post 'create-monthly-email-and-text-checkout-session', to: 'checkouts#create_monthly_email_and_text_checkout_session'
    post 'create-yearly-email-checkout-session', to: 'checkouts#create_yearly_email_checkout_session'
    post 'create-yearly-email-and-text-checkout-session', to: 'checkouts#create_yearly_email_and_text_checkout_session'
  end

  get 'my_lounges', to: 'lounges#my_lounges'
  get 'pricing', to: 'price_listings#pricing'
  get 'success', to: 'purchase/checkouts#success'
  get 'billing', to: 'billing#show'

  authenticate :user, ->(u) { u.admin? } do
    mount Resque::Server.new, at: '/jobs'
  end
end

app/models/rsvp.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: rsvps
#
#  id               :bigint           not null, primary key
#  attended         :boolean          default(FALSE)
#  email            :string
#  first_name       :string
#  last_name        :string
#  number_of_guests :integer
#  phone_number     :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  event_id         :bigint           not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_rsvps_on_email     (email) UNIQUE
#  index_rsvps_on_event_id  (event_id)
#  index_rsvps_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (event_id => events.id)
#  fk_rails_...  (user_id => users.id)
#
class Rsvp < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates_presence_of :first_name, :last_name, :email
  validates :email, uniqueness: true
  validates :number_of_guests, numericality: true

  after_commit :notify_user, on: :create
  after_commit :text_user, on: :create, if: proc { |rsvp| rsvp.phone_number.present? }
  before_save :covert_number_of_guests_to_int

  private

  def notify_user
    email_notification
  end

  def text_user
    return if phone_number.blank?
  
    TwilioClient.new.send_text(phone_number, rsvp_confirmation_message)
  end

  def email_notification
    NewRsvpMailer.with(rsvp: self).notify_user
  end

  def rsvp_confirmation_message
    %(#{user.first_name}, your RSVP has been received for the
      #{event.name} hosted by #{event.lounge.name}!
      Here are the details:
      Event: #{event.name}
      Date: #{event.event_date}
      Start Time: #{event.start_time}
      End Time: #{event.end_time}
      Location: #{event.lounge.address_street_1}, #{event.lounge.city}, #{event.lounge.state}, #{event.lounge.zip_code}
      Phone: #{event.lounge.phone})
  end

  def covert_number_of_guests_to_int
    self[:number_of_guests].to_i
  end
end

app/controllers/rsvps_controller.rb
# frozen_string_literal: true

class RsvpsController < ApplicationController
  before_action :set_rsvp, only: %i[show edit update destroy]
  before_action :set_event, only: %i[index new create]

  def index
    @rsvps = @event.rsvps
  end

  def show; end

  def new
    @rsvp = @event.rsvps.build
  end

  def edit; end

  def create
    @rsvp = @event.rsvps.build(rsvp_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @rsvp.save
        format.turbo_stream { redirect_to rsvp_path(@rsvp) }
        format.html { redirect_to rsvp_url(@rsvp), notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to rsvp_url(@rsvp), notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rsvp.destroy

    redirect_to root_path, status: :see_other
    flash[:notice] = 'RSVP successfully deleted.'
  end

  def mark_attended
    @rsvp = Rsvp.find(params[:id])
    @rsvp.update!(attended: true)
    # deepcode ignore OR: <please specify a reason of ignoring this>
    redirect_to @rsvp
    flash[:notice] = 'RSVP marked as attended.'
  end

  def mark_unattended
    @rsvp = Rsvp.find(params[:id])
    @rsvp.update!(attended: false)
    # deepcode ignore OR: <please specify a reason of ignoring this>
    redirect_to @rsvp
    flash[:notice] = 'RSVP marked as unattended.'
  end

  private

  def set_rsvp
    @rsvp = Rsvp.find(params[:id])
  end

  def set_event
    @event = Event.friendly.find(params[:event_id])
  end

  def rsvp_params
    params.require(:rsvp).permit(:first_name, :last_name, :phone_number, :number_of_guests, :email)
  end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_with(model: [@event, rsvp]) do |form| %>
  <% if rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rsvp.errors.count, "error") %> prohibited this RSVP from being saved:</h2>

      <ul>
        <% rsvp.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control">
    <div class="field">
      <%= form.label :first_name, class: "label" %>
      <%= form.text_field :first_name, class: "input", placeholder: "#{current_user.first_name}" %>
    </div>
  </div>

  <div class="control">
    <div class="field">
      <%= form.label :last_name, class: "label" %>
      <%= form.text_field :last_name, class: "input", placeholder: "#{current_user.last_name}" %>
    </div>
  </div>

  <div class="control">
    <div class="field">
      <%= form.label :number_of_guests, class: "label" %>
      <%= form.number_field :number_of_guests,  in: 1..10, step: 1 %>
    </div>
  </div>

  <div class="control">
    <div class="field">
      <%= form.label :email, class: "label" %>
      <%= form.email_field :email, class: "input", placeholder: "#{current_user.email}" %>
    </div>
  </div>

  <div class="control">
    <div class="field">
      <%= form.label :phone_number, class: "label" %>
      <%= form.telephone_field :phone_number, class: "input", placeholder: "#{current_user.phone_number}" %>
    </div>
  </div>

  <div class="control">
    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/rsvps/_rsvp.html.erb
<div id="<%= dom_id rsvp %>">
  <p>
    <strong>First name:</strong>
    <%= rsvp.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= rsvp.last_name %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= rsvp.phone_number %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= rsvp.email %>
  </p>

    <p>
    <strong>Number of Guests:</strong>
    <%= rsvp.number_of_guests %>
  </p>
</div>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render "form", rsvp: @rsvp %>

<br>

<div>
  <%= link_to "Show this rsvp", @rsvp %> |
  <%= link_to "Back to rsvps", rsvps_path %>
</div>

app/views/rsvps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rsvps</h1>

<div id="rsvps">
  <% @rsvps.each do |rsvp| %>
    <%= render rsvp %>
    <p>
      <%= link_to "Show this rsvp", rsvp %>
    </p>
  <% end %>
</div>

<%= link_to "New rsvp", new_event_rsvp_path(@event) %>

app/views/rsvps/new.html.erb
<%= render "form", rsvp: @rsvp %>

<br>

<div>
  <%= link_to "Back to rsvps", event_rsvps_path(@event) %>
</div>

app/views/rsvps/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rsvp %>

<div>
  <%= link_to "Edit this rsvp", edit_rsvp_path(@rsvp) %> |
  <%= link_to "Back to rsvps", event_rsvps_path(@rsvp.event) %>

  <%= button_to "Destroy this rsvp", @rsvp, method: :delete %>
  <% if @rsvp.attended? %>
    <%= button_to "Mark Unattended", mark_unattended_rsvp_path(@rsvp), method: :patch %>
  <% else %>
    <%= button_to "Mark Attended", mark_attended_rsvp_path(@rsvp), method: :patch %>
  <% end %>
</div>